/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tookasoft.portlet.addtocontacts.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the emailcontact service. Represents a row in the &quot;addtocontactsportlet_emailcontact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.tookasoft.portlet.addtocontacts.model.impl.emailcontactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.tookasoft.portlet.addtocontacts.model.impl.emailcontactImpl}.
 * </p>
 *
 * @author tookasoft
 * @see emailcontact
 * @see com.tookasoft.portlet.addtocontacts.model.impl.emailcontactImpl
 * @see com.tookasoft.portlet.addtocontacts.model.impl.emailcontactModelImpl
 * @generated
 */
public interface emailcontactModel extends BaseModel<emailcontact> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emailcontact model instance should use the {@link emailcontact} interface instead.
	 */

	/**
	 * Returns the primary key of this emailcontact.
	 *
	 * @return the primary key of this emailcontact
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emailcontact.
	 *
	 * @param primaryKey the primary key of this emailcontact
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the email ID of this emailcontact.
	 *
	 * @return the email ID of this emailcontact
	 */
	public long getEmailId();

	/**
	 * Sets the email ID of this emailcontact.
	 *
	 * @param emailId the email ID of this emailcontact
	 */
	public void setEmailId(long emailId);

	/**
	 * Returns the create date of this emailcontact.
	 *
	 * @return the create date of this emailcontact
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this emailcontact.
	 *
	 * @param createDate the create date of this emailcontact
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the email of this emailcontact.
	 *
	 * @return the email of this emailcontact
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this emailcontact.
	 *
	 * @param email the email of this emailcontact
	 */
	public void setEmail(String email);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(emailcontact emailcontact);

	public int hashCode();

	public CacheModel<emailcontact> toCacheModel();

	public emailcontact toEscapedModel();

	public String toString();

	public String toXmlString();
}