/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tookasoft.portlet.addtocontacts.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.tookasoft.portlet.addtocontacts.model.emailaddress;
import com.tookasoft.portlet.addtocontacts.service.emailaddressLocalService;
import com.tookasoft.portlet.addtocontacts.service.emailaddressService;
import com.tookasoft.portlet.addtocontacts.service.persistence.emailaddressPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the emailaddress local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.tookasoft.portlet.addtocontacts.service.impl.emailaddressLocalServiceImpl}.
 * </p>
 *
 * @author tookasoft
 * @see com.tookasoft.portlet.addtocontacts.service.impl.emailaddressLocalServiceImpl
 * @see com.tookasoft.portlet.addtocontacts.service.emailaddressLocalServiceUtil
 * @generated
 */
public abstract class emailaddressLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements emailaddressLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.tookasoft.portlet.addtocontacts.service.emailaddressLocalServiceUtil} to access the emailaddress local service.
	 */

	/**
	 * Adds the emailaddress to the database. Also notifies the appropriate model listeners.
	 *
	 * @param emailaddress the emailaddress
	 * @return the emailaddress that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public emailaddress addemailaddress(emailaddress emailaddress)
		throws SystemException {
		emailaddress.setNew(true);

		return emailaddressPersistence.update(emailaddress, false);
	}

	/**
	 * Creates a new emailaddress with the primary key. Does not add the emailaddress to the database.
	 *
	 * @param emailId the primary key for the new emailaddress
	 * @return the new emailaddress
	 */
	public emailaddress createemailaddress(long emailId) {
		return emailaddressPersistence.create(emailId);
	}

	/**
	 * Deletes the emailaddress with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param emailId the primary key of the emailaddress
	 * @return the emailaddress that was removed
	 * @throws PortalException if a emailaddress with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public emailaddress deleteemailaddress(long emailId)
		throws PortalException, SystemException {
		return emailaddressPersistence.remove(emailId);
	}

	/**
	 * Deletes the emailaddress from the database. Also notifies the appropriate model listeners.
	 *
	 * @param emailaddress the emailaddress
	 * @return the emailaddress that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public emailaddress deleteemailaddress(emailaddress emailaddress)
		throws SystemException {
		return emailaddressPersistence.remove(emailaddress);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(emailaddress.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return emailaddressPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return emailaddressPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return emailaddressPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return emailaddressPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public emailaddress fetchemailaddress(long emailId)
		throws SystemException {
		return emailaddressPersistence.fetchByPrimaryKey(emailId);
	}

	/**
	 * Returns the emailaddress with the primary key.
	 *
	 * @param emailId the primary key of the emailaddress
	 * @return the emailaddress
	 * @throws PortalException if a emailaddress with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public emailaddress getemailaddress(long emailId)
		throws PortalException, SystemException {
		return emailaddressPersistence.findByPrimaryKey(emailId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return emailaddressPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the emailaddresses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of emailaddresses
	 * @param end the upper bound of the range of emailaddresses (not inclusive)
	 * @return the range of emailaddresses
	 * @throws SystemException if a system exception occurred
	 */
	public List<emailaddress> getemailaddresses(int start, int end)
		throws SystemException {
		return emailaddressPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of emailaddresses.
	 *
	 * @return the number of emailaddresses
	 * @throws SystemException if a system exception occurred
	 */
	public int getemailaddressesCount() throws SystemException {
		return emailaddressPersistence.countAll();
	}

	/**
	 * Updates the emailaddress in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param emailaddress the emailaddress
	 * @return the emailaddress that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public emailaddress updateemailaddress(emailaddress emailaddress)
		throws SystemException {
		return updateemailaddress(emailaddress, true);
	}

	/**
	 * Updates the emailaddress in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param emailaddress the emailaddress
	 * @param merge whether to merge the emailaddress with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the emailaddress that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public emailaddress updateemailaddress(emailaddress emailaddress,
		boolean merge) throws SystemException {
		emailaddress.setNew(false);

		return emailaddressPersistence.update(emailaddress, merge);
	}

	/**
	 * Returns the emailaddress local service.
	 *
	 * @return the emailaddress local service
	 */
	public emailaddressLocalService getemailaddressLocalService() {
		return emailaddressLocalService;
	}

	/**
	 * Sets the emailaddress local service.
	 *
	 * @param emailaddressLocalService the emailaddress local service
	 */
	public void setemailaddressLocalService(
		emailaddressLocalService emailaddressLocalService) {
		this.emailaddressLocalService = emailaddressLocalService;
	}

	/**
	 * Returns the emailaddress remote service.
	 *
	 * @return the emailaddress remote service
	 */
	public emailaddressService getemailaddressService() {
		return emailaddressService;
	}

	/**
	 * Sets the emailaddress remote service.
	 *
	 * @param emailaddressService the emailaddress remote service
	 */
	public void setemailaddressService(emailaddressService emailaddressService) {
		this.emailaddressService = emailaddressService;
	}

	/**
	 * Returns the emailaddress persistence.
	 *
	 * @return the emailaddress persistence
	 */
	public emailaddressPersistence getemailaddressPersistence() {
		return emailaddressPersistence;
	}

	/**
	 * Sets the emailaddress persistence.
	 *
	 * @param emailaddressPersistence the emailaddress persistence
	 */
	public void setemailaddressPersistence(
		emailaddressPersistence emailaddressPersistence) {
		this.emailaddressPersistence = emailaddressPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.tookasoft.portlet.addtocontacts.model.emailaddress",
			emailaddressLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.tookasoft.portlet.addtocontacts.model.emailaddress");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return emailaddress.class;
	}

	protected String getModelClassName() {
		return emailaddress.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = emailaddressPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = emailaddressLocalService.class)
	protected emailaddressLocalService emailaddressLocalService;
	@BeanReference(type = emailaddressService.class)
	protected emailaddressService emailaddressService;
	@BeanReference(type = emailaddressPersistence.class)
	protected emailaddressPersistence emailaddressPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private emailaddressLocalServiceClpInvoker _clpInvoker = new emailaddressLocalServiceClpInvoker();
}